language: python
sudo: required
dist: "xenial"
python:
 - "3.6"
 - "3.7"
 - "3.8"
addons:
  apt:
    packages:
      - unixodbc-dev
env:
  global:
    - MSSQL_SA_PASSWORD=Password@123
    # HQ_USERNAME and HQ_API_KEY
    - secure: etv02uWtyy5P4DfyuHjFm5RDFc6WBHLsnIMC75VjDk8kxDgwV/lDbPYMh/hzfPHyskgA1EQbc8IfHlbZWFVV8jOTy+wvrVir/mw95AEyNyAL/TTSWvYfTvdCsxOSbY6vcGlJNfy6rc+y0h6QyuIknY0OhU8sTaRcQnvbFPnOz28=
    - secure: aLj1bKtUF2CnAwG+yjiAjo39cKi9WHaonIwqsuhOx4McsD/xSz4QHv/6/XhXZ5KxKyxw1+PBl/mWo6gyrT5iHDRBPk5iJXqZAgQFS2ukZSv/tUBGL7bWzoO9YfoLuWllA33DCr3PiXAhkH53dTcor16UN9wXeCprBBSGjhpAxRQ=
before_install:
 - docker pull microsoft/mssql-server-linux:2017-latest
 - docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD" -p 1433:1433 --name mssql1 -d microsoft/mssql-server-linux:2017-latest
 - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
 - echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
 - sudo apt-get update -qq
install:
 - sudo apt-get install pandoc
 - python setup.py sdist
 - pip install dist/*
 - pip install pymysql psycopg2 pyodbc
 - pip install coverage coveralls
 - sudo ACCEPT_EULA=Y apt-get install msodbcsql17
before_script:
 - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%';";
 - docker ps -a
 - odbcinst -q -d
 - .travis/wait.sh
script: coverage run setup.py test
after_success:
 - coveralls
services:
 - postgresql
 - mysql
 - docker
